apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
data:
  database_url: cG9zdGdyZXNxbDovL25hbGluZGFsYWwyMDA0OlJocld3UzdQejNaZEBlcC1vbGQtaGlsbC00MzE1MDI1NS51cy1lYXN0LTIuYXdzLm5lb24udGVjaC9wYXl0bT9zc2xtb2RlPXJlcXVpcmU
